camel:
  springboot:
    main-run-controller: true
    routes-include-pattern: classpath:camel/*.xml

spring:
  activemq:
    user: admin
    password: admin

app:
  queue:
    consume: "jms:queue:CONSUMER_QUEUE"
    produce: "jms:queue:RECEIVER_QUEUE"